# SPDX-FileCopyrightText: 2025 diggsweden/wallet-provider
#
# SPDX-License-Identifier: CC0-1.0

# Artifacts Configuration for wallet-provider
# Defines what to build and where to publish

artifacts:
  - name: wallet-provider
    project-type: maven
    working-directory: .
    build-type: application
    config:
      java-version: 21

containers:
  - name: wallet-provider
    from: [wallet-provider]
    container-file: Containerfile
    context: .
    platforms: linux/amd64,linux/arm64
    registry: ghcr.io

publishers:
  - type: github-packages
    artifacts: [wallet-provider]
