# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: EUPL-1.2

wua:
  keystore:
    location: file:src/test/resources/certificates/wallet-provider.p12
    password: secret
    alias: wallet-provider
    type: PKCS12
