# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: EUPL-1.2

server:
  port: 8080
spring:
  application:
    name: wallet-provider
  profiles:
    active: dev
  docker:
    compose:
      enabled: false

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

wua:
  keystore:
    location: ${WUA_KEYSTORE_PATH}
    password: ${WUA_KEYSTORE_PASSWORD}
    alias: ${WUA_KEYSTORE_ALIAS}
    type: PKCS12
