# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
# SPDX-License-Identifier: EUPL-1.2

blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/diggsweden/wallet-provider/security/advisories/new
    about: Please report security vulnerabilities through GitHub Security Advisories
  - name: Questions and Discussions
    url: https://github.com/diggsweden/wallet-provider/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/diggsweden/wallet-provider/blob/main/README.md
    about: Check the documentation for usage instructions and guides
